package gui;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

import utils.Entity;

public class AddNewForm extends JDialog {
  private JTextField tfName;
  private JTextField tfId;
  private JCheckBox cb;
  private JLabel lbName;
  private JLabel lbId;
  private JLabel lbProp;
  private JTextField tfProperty;
  private JLabel lbValue;
  private JTextField tfValue;
  private JList jList;
  private JButton btnEntenty;
  private JButton btnProperty;
  private JLabel lbParent;
  private JTextField tfParent;
  private DefaultListModel<String> listModel = new DefaultListModel<>();

  public AddNewForm() {
      //construct preComponents

      //construct components
      tfName = new JTextField (5);
      tfId = new JTextField (5);
      cb = new JCheckBox ("Manual ID");
      lbName = new JLabel ("Name:");
      lbId = new JLabel ("ID:");
      lbProp = new JLabel ("Property:");
      tfProperty = new JTextField (5);
      lbValue = new JLabel ("Value:");
      tfValue = new JTextField (5);
      jList = new JList (listModel);
      btnEntenty = new JButton ("Add Ententy");
      btnProperty = new JButton ("Add Property");
      lbParent = new JLabel ("Parent ID:");
      tfParent = new JTextField (5);

      //adjust size and set layout
      setPreferredSize (new Dimension (746, 574));
      setLayout (null);

      //add components
      add (tfName);
      add (tfId);
      add (cb);
      add (lbName);
      add (lbId);
      add (lbProp);
      add (tfProperty);
      add (lbValue);
      add (tfValue);
      add (jList);
      add (btnEntenty);
      add (btnProperty);
      add (lbParent);
      add (tfParent);

      //set component bounds (only needed by Absolute Positioning)
      tfName.setBounds (210, 55, 100, 25);
      tfId.setBounds (210, 95, 100, 25);
      cb.setBounds (330, 95, 100, 25);
      lbName.setBounds (75, 55, 100, 25);
      lbId.setBounds (75, 95, 100, 25);
      lbProp.setBounds (75, 135, 100, 25);
      tfProperty.setBounds (210, 135, 100, 25);
      lbValue.setBounds (335, 135, 100, 25);
      tfValue.setBounds (445, 135, 100, 25);
      jList.setBounds (75, 230, 470, 130);
      btnEntenty.setBounds (370, 405, 115, 25);
      btnProperty.setBounds (585, 135, 150, 25);
      lbParent.setBounds (75, 175, 100, 25);
      tfParent.setBounds (210, 175, 100, 25);
      
      tfId.setEditable(false);
      
      cb.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			if (cb.isSelected())
				tfId.setEditable(true);
			else
				tfId.setEditable(false);
		}
	});
      btnProperty.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			if(!(tfProperty.getText().equals("")||tfValue.getText().equals(""))) {
				String str = tfProperty.getText()+":"+tfValue.getText();
				tfProperty.setText("");
				tfValue.setText("");
				listModel.addElement(str);
				jList.updateUI();
			}
		}
	});
      
      btnEntenty.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			Entity ent = new Entity();
			ent.setNaziv(tfName.getText());
			for(int i=0;i<listModel.getSize();i++)
			{
				String[] str = listModel.getElementAt(i).split(":");
				ent.addSimpleProperty(str[0], str[1]);
			}
			if(cb.isSelected())
			{
				Boolean flag = MainFrame.getInstance().getStorage().addEntity(ent, Integer.parseInt(tfId.getText()));
				if(!flag)
					System.err.println("Postoji ID");
				
			}
			else if (!(tfParent.getText().equals("")))
			{
				MainFrame.getInstance().getStorage().addEntity(ent, tfParent.getText(), "0");
			}
			else
				MainFrame.getInstance().getStorage().addEntity(ent);
		}
	});
      
      setSize(830, 600);
      setLocationRelativeTo(null);
  }
}

